name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    continue-on-error: true # TODO(sashayakovtseva): remove this when repo is cleaned up.
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.50.1-alpine
    steps:
      - uses: actions/checkout@v3.0.2
      - run: apk add make
      - run: make lint

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.19
      - run: make test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [check, unit-test]
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.19
      - run: make integration-test
